"""empty message

Revision ID: 14b29768b468
Revises: None
Create Date: 2015-03-29 20:55:45.343338

"""

# revision identifiers, used by Alembic.
revision = '14b29768b468'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
